### ISSUE TITLE
package abandoned?

### ISSUE THREAD

**Issue by ivpusic** [Sunhat/react-native-extra-dimensions-android#11]
just a question...are you still maintaining this module?

**Comment by Sunhat** [comment]
jaysoo does not appear to be maintaining this package. This package is does not appear to be compatible with the latest version of React Native (0.37) - I'll fork this and update it

**Comment by jaysoo** [comment]
@ivpusic @Sunhat I haven't had any time to maintain this. If anyone wants to take over, please PM or email me.
