### ISSUE TITLE
Build failed on android device after upgrade the RN version to 0.38.0

### ISSUE THREAD

**Issue by susan-github** [Sunhat/react-native-extra-dimensions-android#15]
**RN Version:** 0.38.0
**extra-dimensions Version:** 0.18.0
**Descriptions:**
Build failed through 'react-native run-android' command， I have been told "could not find any version that matches com.facebook.react:react-native:0.37.+.". But I have installed 0.38.0.
**ScreenShot:**
<img width="639" alt="dingtalk20161130114417" src="https://cloud.githubusercontent.com/assets/9947305/20739026/767e7e8c-b6f2-11e6-87a2-a564d1895094.png">

**Comment by susan-github** [comment]
And I modified 'react-native-extra-dimensions-android/android/build.gradle' dependencies as 'com.facebook.react:react-native:+',  then app can build success. So if you can consider to use 'react-native:+' instead of 'react-native:0.37.+'

**Comment by Sunhat** [comment]
Hi, this issue was resolved 2 days ago - I forgot to publish this to npm. Thanks!

**Comment by susan-github** [comment]
Thanks for you update.:)
