### ISSUE TITLE
ExtraDimensions is {}

### ISSUE THREAD

**Issue by duzliang** [Sunhat/react-native-extra-dimensions-android#16]
`"react-native": "^0.37.0"`

`import ExtraDimensions from 'react-native-extra-dimensions-android';`
ExtraDimensions is {} object

**Comment by Sunhat** [comment]
I'll take a look into this now. Did you install `rnpm` and run `rnpm link`

**Comment by duzliang** [comment]
I have installed this package before and but not work for RN 0.29+
I reinstall this package and everything is ok, thanks @Sunhat
