### ISSUE TITLE
ExtraDimensions is undefined

### ISSUE THREAD

**Issue by code-by** [Sunhat/react-native-extra-dimensions-android#17]
I have followed all instructions, but got
`undefined is not an object (evaluating '_reactNative.NativeModules.ExtraDimensions[dim]'`

My code is:
```
import ExtraDimensions from 'react-native-extra-dimensions-android';
...
console.log(ExtraDimensions.get('REAL_WINDOW_WIDTH'));
```

I have RN ver 0.42

**Comment by Sunhat** [comment]
Hi, apologies for the delayed response here.

Firstly have you run rnpm link

Secondly double check the MainActivity.java file (check README)

Thirdly, I will be testing this as soon as I get the chance

**Comment by infinityl00p** [comment]
I'm running into the same issue RN 0.52, any fix yet?

**Comment by metahexane** [comment]
Bringing this back on topic, since I just can't use it without ejecting (and that's really not what I want to do). Is this not possible to do without ejecting (so just CRNA and Expo)?

**Comment by Josh-Rosen** [comment]
I'm also experiencing this issue

**Comment by Sunhat** [comment]
> I'm also experiencing this issue

What version of RN are you using?

**Comment by Sunhat** [comment]
If you do experience this issue, I imagine a quick `react-native run-android` will fix it, by rebuilding the project for you.

**Comment by Jeijie** [comment]
+1, RN 0.55.4

**Comment by nnzbz** [comment]
I'm also experiencing this issue.
Is it Expo's problem?

**Comment by Sunhat** [comment]
This issue seems to only occur when initially installing the package. It requires a full re-compile.

**Comment by eddietex** [comment]
A feature requested was created on Expo's Canny to start supporting this library by default on Expo managed projects. Those of you interested, feel free to vote up: https://expo.canny.io/feature-requests/p/react-native-extra-dimensions-android
