### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by XavierColombel** [Sunhat/react-native-extra-dimensions-android#22]
I've got an error while building a project with this component. Here is a screenshot of the error:

![capture](https://img4.hostingpics.net/pics/314092Capturedecran20170824a155555.png)

I've linked component auto and manual and check **MainApplication.java** file.

I've cleaned/rebuilt project and restarted the packager.

I'm using react-native v0.47.2.

**Comment by Sunhat** [comment]
Hi, sorry for the delay. I updated this repo for 0.47, however I forgot to update the package version & npm.

I'll do this now
