### ISSUE TITLE
error: package com.jaysoo.extradimensions does not exist

### ISSUE THREAD

**Issue by Stettinum** [Sunhat/react-native-extra-dimensions-android#28]
when react-native run-android build fails with message above

error: package com.jaysoo.extradimensions does not exist

**Comment by NickAlvesX** [comment]
Same issue here, how did you solve this?

**Comment by NickAlvesX** [comment]
Solved. 
I had to add `implementation project(':react-native-extra-dimensions-android')` at `dependencies` of `android/app/build.gradle`
