### ISSUE TITLE
ExtraDimensionsPackage is not abstract and does not override abstract method createJSModules() in ReactPackage public class ExtraDimensionsPackage implements ReactPackage {

### ISSUE THREAD

**Issue by Stettinum** [Sunhat/react-native-extra-dimensions-android#29]
I get this error when run react-native run-android
ExtraDimensionsPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ExtraDimensionsPackage implements ReactPackage {

**Comment by vtam311** [comment]
+1 getting same error as well

**Comment by Stettinum** [comment]
@waterdoo  i had react-native version 0.39.0 and that error occurs. I solved it by update react-native to version 0.48.3. Seems it not supported lower versions of react. If you upgrade RN remember to update also react to version 'react@16.0.0-alpha.12'

**Comment by wmonecke** [comment]
+1 cannot compile android today because of this...

**Comment by Stettinum** [comment]
@wmonecke  upgrade react native to version 0.48.3
