### ISSUE TITLE
Native module ExtraDimensionsModule tried to override ExtraDimensionsModule for module name ExtraDimensions. If this was your intention, set canOverrideExistingModule=true

### ISSUE THREAD

**Issue by gao520sun** [Sunhat/react-native-extra-dimensions-android#31]
react-native : 0.46.4
' new ExtraDimensionsPackage()', No duplicate

**Comment by hanyoureal** [comment]
in android/app/src/main/java/../../MainApplication.java

where you have:
```
protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
```

check if you have duplicate 
```
new ExtraDimensionsPackage()
```
 or any other packages

i think this happened to me because i manually fixed the indentation of the classes added by running 'link' but i have to test it again to confirm
