### ISSUE TITLE
Please get rid of console warning

### ISSUE THREAD

**Issue by ekimlinger** [Sunhat/react-native-extra-dimensions-android#34]
Whenever the platform is not on android, there is a warning that displays:
```
  console.warn node_modules/react-native-extra-dimensions-android/index.js:11
    react-native-extra-dimensions-android is only available on Android
```

This is not needed and only serves to clutter the console. Anyone with a brain knows that this package is only going to be applicable/used on android. This warning message shows up even on tests.

**Comment by Sunhat** [comment]
It's been a while since I've used this (or react, since it's total crap) - I've moved the console.warn to inside of the get method, this should mean the console.warn only displays when **called** on iOS
