### ISSUE TITLE
Show Error like 'undefined is not an object(evaluating 'ExtraDimensions[dim]')'

### ISSUE THREAD

**Issue by llgoer** [Sunhat/react-native-extra-dimensions-android#4]
I use the plugin 'react-native-gifted-messenger',the example use '"react-native-extra-dimensions-android": "^0.17.0",',but i run the project in android platform.the error like  'undefined is not an object(evaluating 'ExtraDimensions[dim]')'.

**Comment by FaridSafi** [comment]
Hello @yanghuxiao, did you modify the .gradle files and MainActivity.java ? https://github.com/jaysoo/react-native-extra-dimensions-android#installation

**Comment by llgoer** [comment]
...
