### ISSUE TITLE
SOFT_MENU_BAR_HEIGHT is wrong on Pixel 3 XL

### ISSUE THREAD

**Issue by mathieubruguier** [Sunhat/react-native-extra-dimensions-android#43]
Thanks for making/maintaining this library.

I've run into an issue where SOFT_MENU_BAR_HEIGHT seems to be double the value it should be when running on a Pixel 3 XL with the notch activated (default behavior).

See screenshots for more information:

This is running on a Pixel 3 XL with the notch deactivated (display cutout hidden in developer options).
![image](https://user-images.githubusercontent.com/792891/53364954-d64c2180-38f4-11e9-8256-05fe240e9589.png)

This is running on a Pixel 3 XL with the notch activated (display cutout set to "Device default" in developer options)
![image](https://user-images.githubusercontent.com/792891/53365013-ff6cb200-38f4-11e9-8215-38aa177bcea1.png)

As you can see, SOFT_MENU_BAR_HEIGHT is reported as ~96, which is wrong since it's the exact same height as it was with the notch deactivated.
Let me know if you need any more information and I'd be happy to provide it.

**Comment by Sunhat** [comment]
Thanks a lot for reporting this. Quite peculiar. I'll look into this as soon as I can

**Comment by terryttsai** [comment]
I'm seeing the exact same issue on my Essential phone

**Comment by manuhook** [comment]
Same here, you can reproduce this behavior with an emulator with Android Pie and the option "Simulate a Display With a Cutout".
On each physical device with a cutout or a notch I've tried the SOFT_MENU_BAR_HEIGHT  is twice the value it should be.

**Comment by mathieubruguier** [comment]
I dug into the code and opened a PR for a fix: https://github.com/Sunhat/react-native-extra-dimensions-android/pull/50

**Comment by mathieubruguier** [comment]
Issue was fixed with #50. Closing!
