### ISSUE TITLE
Configuration with name 'default' not found

### ISSUE THREAD

**Issue by ferologics** [Sunhat/react-native-extra-dimensions-android#5]
A problem occurred configuring project ':app'.

> Cannot evaluate module ExtraDimensions : Configuration with name 'default' not found.

this happened after I went through installation steps.

**Comment by ferologics** [comment]
didn't "npm i react-native-extra-dimensions-android"

can you edit the readme to say "npm i react-native-extra-dimensions-android" as the first thing before installing anything else? doesn't look like a node module

**Comment by ankuj** [comment]
I had the same problem, thanks for posting the solution.

The documentation still doesn't look any better, not sure if its being monitored.

**Comment by ferologics** [comment]
submitted a PR, will wait until merged, then close
