### ISSUE TITLE
ExtraDimensions.get('SOFT_MENU_BAR_HEIGHT') return 0

### ISSUE THREAD

**Issue by hehex9** [Sunhat/react-native-extra-dimensions-android#6]
I am using Meizu for test.

**Comment by ms88privat** [comment]
Maybe not related, but this is what I'm using to determine the device height across android devices

```js
DEVICE_HEIGHT =
    ExtraDimensions.get('REAL_WINDOW_HEIGHT') -
    (Platform.Version > 19 ? 0 : ExtraDimensions.get('STATUS_BAR_HEIGHT')) -
    ExtraDimensions.get('SOFT_MENU_BAR_HEIGHT');
```

You need to set the StatusBar to translucent to make this work correctly
```
<StatusBar
            backgroundColor='#636363'
            barStyle='default'
            translucent
            />
```

**Comment by duzliang** [comment]
`"react": "^15.4.1",`
`"react-native": "^0.38.0",`
`"react-native-extra-dimensions-android": "^0.20.1",`

Android: Xiaomi  MI 4s , Android 5.1.1 , API 22

+1

**Comment by duzliang** [comment]
it's my wrong to test this on Xiaomi mobile, because the MIUI doesn't have no soft menu bar.
this is work on HUAWEI mobile phone and it work conrect

**Comment by sandropoluan** [comment]
Meizu doesn't have soft menu bar.
that is why it return 0.  
Try use SMART_BAR_HEIGHT  instead.
