### ISSUE TITLE
it's can't work with RN 0.29+

### ISSUE THREAD

**Issue by lekenny** [Sunhat/react-native-extra-dimensions-android#9]
customizations has been moved to  MainApplication.java

**Comment by beinginorbit** [comment]
Same issue, not sure where to get the `Activity` instance for this module to work.

It also breaks `react-native-orientation` https://github.com/yamill/react-native-orientation/issues/83.
And `react-native-push-notification` https://github.com/zo0r/react-native-push-notification
And `react-native-gcm-android` https://github.com/oney/react-native-gcm-android/issues/65

**Comment by jerson** [comment]
from release notes https://github.com/facebook/react-native/releases

```
Plugins which pass activity reference in the constructor need to be updated to extend     
ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. 
This change is backward compatible.
```

**Comment by BelinChung** [comment]
Hi, the following is the working version for RN0.29  :)
https://github.com/BelinChung/react-native-extra-dimensions-android/commit/6f1a73d31787b7e13cf4f36eee2bb9c7332f69a1

**Comment by sibelius** [comment]
@BelinChung please submit a PR to fix this, then @jaysoo can review

**Comment by BelinChung** [comment]
@sibelius https://github.com/jaysoo/react-native-extra-dimensions-android/pull/10

**Comment by luisfuertes** [comment]
Compile error with `"react-native": "0.29.0",`and `"react-native-extra-dimensions-android": "^0.17.0",`

```
error: constructor ExtraDimensionsPackage in class ExtraDimensionsPackage cannot be applied to given types;
          new ExtraDimensionsPackage()
```

With new react versions it must write on MainApplication.java, instead of MainActivity.java.

**Comment by Larney11** [comment]
@luisfuertes I have done what you said and still no luck. Would you mind having a look at [this issue](https://github.com/jaysoo/react-native-extra-dimensions-android/issues/13) I created I think it might be a similar problem. Much appreciated! #13

**Comment by luisfuertes** [comment]
@Larney11 i cant solved it. Finally i didnt use this component.

**Comment by Larney11** [comment]
@BelinChung Why is the [repository](https://github.com/BelinChung/react-native-extra-dimensions-android/commit/6f1a73d31787b7e13cf4f36eee2bb9c7332f69a1) you shared the same. Is it available on NPM? Is this the error you were receiving? #13

**Comment by Larney11** [comment]
@luisfuertes Scary. Thanks for the reply.

**Comment by Larney11** [comment]
@luisfuertes What component did you use??

**Comment by luisfuertes** [comment]
For this none :(

**Comment by BelinChung** [comment]
RN  is not stable version now, every version may have breaking change.
Not all authors have the time to maintain third-party plug.
The best way is fork it and maintain by yourself.

![image](https://cloud.githubusercontent.com/assets/4954264/17160988/1412035a-53dc-11e6-8d32-11ce51f360b0.png)

**Comment by IjzerenHein** [comment]
For the record, I you just want to get the height of the status-bar, you can use plain react-native code:

``` js
import {StatusBar} from 'react-native'
console.log('statusBarHeight: ', StatusBar.currentHeight);
```

**Comment by Larney11** [comment]
Thanks BelinChung.

**Solution**
[Check out this StackOverflow solution](http://stackoverflow.com/questions/38592302/react-native-android-how-to-use-getrealdimensions-dimensions-is-not-working/38804173#38804173).
@luisfuertes

**Comment by esutton** [comment]
> from release notes https://github.com/facebook/react-native/releases
> 
> Plugins which pass activity reference in the constructor need to be updated to extend  
> ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. 
> This change is backward compatible.

@jerson How do you do you change MainApplication to extend ReactContextBaseJavaModule?

Sorry, I  have low Java experience.

```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new BluetoothIOPackage(this), //<- How pass the Activity to a plugin ?
          new VectorIconsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by BelinChung** [comment]
Hi, all
After RN0.31.0 you can use `getCurrentActivity()` method to access current activity. it is more simple than my method, but this method is NOT backward compatible.
Checkout this commit for detail: https://github.com/facebook/react-native/commit/760656461197605ee26769ed73989f78e4753038
